// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const removeAllUsers = `-- name: RemoveAllUsers :exec
DELETE FROM users
`

func (q *Queries) RemoveAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeAllUsers)
	return err
}
